import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
import {template,blocks,catalog,seed} from '../src/generated.js';
import {validateDraft,pending,renderGuide} from '../src/content.js';
test('all tabs and representative photographs are editable',()=>{for(const b of ['I18N','HOUSE_NOTES','MANUALS','food','ARANYA_CURATED_PLACES','hero'])assert(catalog.some(f=>f.block===b));assert(catalog.filter(f=>f.type==='image').length>=2);});
test('Korean edits invalidate translation and cannot fake completion',()=>{const draft=structuredClone(seed),id=catalog.find(f=>f.type==='text').id;draft[id].values.ko='새 안내';draft[id].translatedFrom='새 안내';const result=validateDraft(draft,catalog,seed);assert(pending(result,catalog).includes(id));assert.equal(seed[id].translatedFrom,seed[id].values.ko);});
test('malicious HTML and external image URLs rejected',()=>{const draft=structuredClone(seed),id=catalog.find(f=>f.type==='text').id;draft[id].values.ko='<img src=x onerror=alert(1)>';assert.throws(()=>validateDraft(draft,catalog,seed));const photo=structuredClone(seed),image=catalog.find(f=>f.type==='image').id;photo[image].values.ko='https://external.example/x.svg';assert.throws(()=>validateDraft(photo,catalog,seed));});
test('guide has valid scripts, extracted photos, server login and preserved guest expiry',()=>{const html=renderGuide(template,blocks,catalog,seed);assert(!html.includes('__ARANYA_'));assert(!/data:image\/(png|jpeg|webp);base64/.test(html));assert(!html.includes('ADMIN_HASH'));assert(html.includes('/api/login'));assert(html.includes('function isGuestExpired'));for(const m of html.matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)){if(m[1].includes('application/json'))JSON.parse(m[2]);else new vm.Script(m[2]);}});
test('deploy directory excludes repository and source',()=>{assert(!fs.existsSync('dist/.git'));assert(!fs.existsSync('dist/wrangler.jsonc'));assert(!fs.existsSync('dist/src'));});

