// Local browser regression review. Requires scripts/review-server.mjs --test-ai.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
const base='http://127.0.0.1:8790';
const png={name:'management-review.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a4WQAAAAASUVORK5CYII=','base64')};
(async()=>{
 const browser=await chromium.launch({channel:process.env.BROWSER_CHANNEL||'chrome',headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 const api=(path,body)=>page.evaluate(async({path,body})=>{const r=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(r.status+': '+data.error);return data;},{path,body});
 const frame=()=>page.frameLocator('#guideFrame');
 const ready=()=>page.waitForFunction(()=>document.getElementById('save')&&!document.getElementById('save').disabled);
 try{
  await page.goto(base+'/');await page.locator('#hostBasePassword').fill('local-review-only');await page.locator('#hostBaseUnlock').click();await page.getByRole('link',{name:'내용 관리',exact:true}).waitFor();
  await page.getByRole('link',{name:'내용 관리',exact:true}).click();await page.locator('#manager').waitFor();assert.equal(await page.locator('#login').isVisible(),false);await frame().locator('#greetTag').waitFor();console.log('PASS single host login opens content manager');
  assert.equal(await page.locator('header .admin-brand').textContent(),'아란야 · Aranya');
  assert.equal(await page.locator('.managed-add select').count(),0);
  // Normalize only old local test edits so the publish check has a known baseline.
  let state=await api('content');for(const id of state.pending)state.draft[id].values.ko=state.draft[id].translatedFrom;await api('draft',{revision:state.revision,draft:state.draft});await page.reload();await page.locator('#manager').waitFor();
  const label='검증 식당 '+Date.now();await page.locator('#sections [data-section="food"]').click();const foodList=page.locator('[data-list-key="food:"]');const count=await foodList.locator('.managed-row').count();await foodList.locator('.managed-add button').click();await page.waitForFunction(n=>document.querySelectorAll('[data-list-key="food:"] .managed-row').length===n,count+1);await ready();
  state=await api('content');const item=state.lists.find(l=>l.key==='food:').items.at(-1);await page.locator('#fields > .card > textarea').fill(label);await page.locator('#save').click();await ready();await frame().locator('#foodList h3').filter({hasText:label}).waitFor();console.log('PASS add item and saved draft preview');
  const guestContext=await browser.newContext(),guest=await guestContext.newPage();guest.on('pageerror',e=>errors.push('guest: '+e.message));const packed=Buffer.from(JSON.stringify(['Guest','2099-01-01','2099-01-03','15:00','11:00',2,0,'ko'])).toString('base64url');await guest.goto(base+'/?g='+packed);assert(!(await guest.content()).includes(label));console.log('PASS unpublished item is not visible to guests');
  const row=()=>page.locator('[data-list-key="food:"] [data-item-id="'+item.id+'"]');await row().getByRole('button',{name:'↑',exact:true}).click();await ready();state=await api('content');assert.equal(state.lists.find(l=>l.key==='food:').items.at(-2).id,item.id);console.log('PASS reorder preserves item identity');
  await page.locator('#sections [data-section="images"]').click();assert.equal(await page.locator('#addPhotoToItem').isDisabled(),true);await page.locator('#photoTargetSection').selectOption('food');await page.locator('#photoTargetItem').selectOption(item.key);assert((await page.locator('#photoTargetItem option:checked').textContent()).includes(label));await page.locator('#addPhotoToItem').click();await ready();await frame().locator('.page.active[data-page="home"]').waitFor();await page.locator('#fields input[type=file]').setInputFiles(png);await page.waitForFunction(()=>document.querySelector('#fields img')?.getAttribute('src')?.startsWith('/media/'));await page.locator('#save').click();await ready();await page.locator('#sections [data-section="food"]').click();
  state=await api('content');const photos=state.photos.find(p=>p.key===item.key);const photoId=photos.fieldIds[0],image=state.draft[photoId].values.ko;await frame().locator('[data-guide-photo="'+image+'"]').waitFor();assert.equal(photos.itemKey,item.key);console.log('PASS photo menu targets the selected new item and preview');await page.locator('#sections [data-section="food"]').click();
  await row().locator('.managed-title').click();await page.getByRole('button',{name:'이 문구 다시 번역',exact:true}).click();await ready();state=await api('content');assert.equal(state.pending.length,0);assert(state.draft[item.titleId].values.en.startsWith('[TEST en]'));console.log('PASS new item uses translation review workflow (local stub only)');
  await page.locator('#publish').click();await page.locator('#reviewed').check();await page.locator('#confirmPublish').click();await ready();await guest.reload();assert((await guest.content()).includes(label));assert((await guest.content()).includes(image));console.log('PASS published new item and photo appear to fresh guests');
  await row().getByRole('button',{name:'삭제',exact:true}).click();await ready();state=await api('content');assert(!state.draft[item.titleId]);assert(!state.draft[photoId]);await guest.reload();assert((await guest.content()).includes(label));console.log('PASS deleting draft item preserves published item until publish');
  await page.locator('#publish').click();await page.locator('#reviewed').check();await page.locator('#confirmPublish').click();await ready();await guest.reload();assert(!(await guest.content()).includes(label));console.log('PASS published deletion removes guest item');
  await page.goto(base+'/');assert.equal(await page.locator('#hostBasePassword').isVisible(),false);await page.getByRole('link',{name:'내용 관리',exact:true}).click();await page.locator('#manager').waitFor();await page.reload();await page.locator('#manager').waitFor();assert.equal(await page.locator('#login').isVisible(),false);console.log('PASS navigation and reload retain server login');
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'.wrangler/review/management-mobile.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'.wrangler/review/management-desktop.png',fullPage:true});console.log('PASS mobile layout');
  const unauthorized=await guest.evaluate(()=>fetch('/api/structure',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}).then(r=>r.status));assert.equal(unauthorized,401);
  await page.locator('#logout').click();await page.locator('#login').waitFor();assert.deepEqual(errors,[]);console.log('PASS logout, guest API protection and no browser errors');
 }catch(error){await page.screenshot({path:'.wrangler/review/management-failure.png',fullPage:true});console.error('Browser errors:',errors);throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
