const {chromium}=require('C:/Users/hot90/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const marker='공항 안내 검증 '+Date.now();const base='http://127.0.0.1:8790';await page.goto(base+'/admin');await page.locator('#password').fill('local-review-only');await page.locator('#loginForm button').click();const frame=page.frameLocator('#guideFrame');await frame.locator('#homeBrand').waitFor();
const idle=()=>page.waitForFunction(()=>!document.getElementById('save').disabled);await idle();
const api=async(path,body)=>{const r=await page.evaluate(async({path,body})=>{const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});return {status:r.status,data:await r.json()};},{path,body});assert.equal(r.status,200,JSON.stringify(r.data));return r.data;};
let data=await api('content');assert(data.catalog.some(f=>f.id==='AIRPORT:button'));assert(data.catalog.some(f=>f.id==='TRAVEL_TIPS:0.steps.0.body'));
// Actual editor selection, typing and in-place preview.
await page.locator('#fieldBrowser').evaluate(e=>e.open=true);await page.locator('[data-field-id="AIRPORT:button"]').click();const input=page.locator('#fields textarea').first();await input.fill(marker);await page.locator('#save').click();await idle();
const guest=await context.newPage(),g=Buffer.from(JSON.stringify(['Preview','2099-01-01','2099-01-03','15:00','11:00',2,0,'ko'])).toString('base64');await guest.goto(base+'/?g='+encodeURIComponent(g));assert(!(await guest.content()).includes(marker));
await frame.locator('#airportGuide').waitFor();assert.equal(await frame.locator('#airportGuide').getAttribute('open'),null);await page.locator('#browseMode').click();await frame.locator('#airportGuide summary').click();assert(await frame.locator('#airportGuide').evaluate(e=>e.open));await frame.locator('#airportGuide summary').click();assert.equal(await frame.locator('#airportGuide').evaluate(e=>e.open),false);
// Translate through the real endpoint with the local test AI adapter.
data=await api('content');data=await api('translate',{revision:data.revision,id:'AIRPORT:button'});for(const l of ['en','zh','ja','de','fr','es','it','pt','ru'])assert(data.draft['AIRPORT:button'].values[l].includes('[TEST'));
data=await api('publish',{revision:data.revision,reviewed:true});await guest.reload();assert((await guest.content()).includes(marker));
// UI structure controls: airport add, reorder, delete, then tips card and details.
await page.reload();await frame.locator('#homeBrand').waitFor();await idle();page.on('dialog',d=>d.accept());
async function mutateList(key){const list=page.locator('[data-list-key="'+key+'"]');if(!await list.evaluate(e=>e.open))await list.locator(':scope > summary').click();await list.locator(':scope > .managed-add button').click();await idle();let rows=list.locator(':scope > .managed-row');const id=await rows.last().getAttribute('data-item-id');await rows.last().getByRole('button',{name:'↑',exact:true}).click();await idle();await list.locator('[data-item-id="'+id+'"]').getByRole('button',{name:'삭제',exact:true}).click();await idle();}
await mutateList('AIRPORT:methods');await page.locator('[data-section="tips"]').click();await mutateList('TRAVEL_TIPS:');await page.locator('[data-list-key="TRAVEL_TIPS:"] .managed-title').first().click();await mutateList('TRAVEL_TIPS:0.steps');
await frame.locator('.tab[data-page="tips"]').click();await frame.locator('[data-cms-field="TRAVEL_TIPS:0.description"]').click();assert(await page.locator('#fields textarea').first().evaluate(e=>e===document.activeElement));
// Gallery creation and actual local R2 upload through the normal file input.
await page.locator('[data-section="images"]').click();await page.locator('#photoTargetSection').selectOption('tips');await page.locator('#photoTargetItem').selectOption('TRAVEL_TIPS:0');await page.locator('#addPhotoToItem').click();await idle();
await page.locator('#fields input[type=file]').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+a0ZkAAAAASUVORK5CYII=','base64')});await idle();await page.locator('#save').click();await idle();assert(await page.locator('#fields img').isVisible());
// Public layout and language switching, including mobile.
for(const width of [1440,390]){await guest.setViewportSize({width,height:900});await guest.locator('.tab[data-page="tips"]').click();for(const lang of ['ko','en','zh','ja','de','fr','es','it','pt','ru']){await guest.locator('#langBtn').click();await guest.locator('#langMenu [data-lang="'+lang+'"]').click();assert(await guest.locator('#travelTipsContent h3').first().textContent());assert(await guest.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));}await guest.screenshot({path:'.wrangler/review/travel-'+width+'.png',fullPage:true});}
for(const section of ['around','food','manuals','amenities']){await guest.locator('.tab[data-page="'+section+'"]').click();assert(await guest.locator('.page[data-page="'+section+'"] h2').first().isVisible());}
await api('logout',{});assert.equal((await page.request.get(base+'/api/content')).status(),401);await api('login',{password:'local-review-only'});assert((await api('content')).draft['AIRPORT:button'].values.ko===marker);
const expired=Buffer.from(JSON.stringify(['Test','','2000-01-01','','11:00',1,0,'ko'])).toString('base64');assert.equal((await page.request.get(base+'/?g='+encodeURIComponent(expired))).status(),410);assert.deepEqual(errors,[]);
console.log('PASS desktop/mobile, ten languages, editor selection, lists CRUD/reorder, upload, translation adapter, draft isolation/publish, relogin, expiry and existing sections');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
